name: Build IPQ807x
on: 
    push:
    workflow_dispatch:

jobs:
    build:
        name: Prepare and build IPQ807x generic images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for IPQ807x Generic
              run: |
                echo "CONFIG_TARGET_ipq807x=y" > .config
                echo "CONFIG_TARGET_ipq807x_generic=y" >> .config
                echo "CONFIG_TARGET_ipq807x_generic_DEVICE_xiaomi_ax3600=y" >> .config
                echo "CONFIG_TARGET_ROOTFS_INITRAMFS=y" >> .config
                
                echo "CONFIG_PACKAGE_nss-firmware-ipq8074=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-bridge-mgr=y" >> .config

                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-clmapmgr=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-dtlsmgr=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-eogremgr=y" >> .config

                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-gre=y" >> .config

                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-l2tpv2=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-lag-mgr=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-map-t=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-match=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-netlink=y" >> .config

                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-pppoe=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv-vlan-mgr=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-ssdk=y" >> .config                
                echo "CONFIG_PACKAGE_qca-ssdk-shell=y" >> .config

                echo "CONFIG_PACKAGE_luci=y" >> .config
                echo "CONFIG_PACKAGE_wpad-basic-mbedtls=m" >> .config
                echo "CONFIG_PACKAGE_wpad-mbedtls=y" >> .config
                echo "CONFIG_PACKAGE_luci-statistics=y" >> .config
                echo "CONFIG_PACKAGE_luci-i18n-statistics-es=y" >> .config
                echo "CONFIG_PACKAGE_luci-i18n-opkg-es=y" >> .config
                echo "CONFIG_PACKAGE_luci-lua-runtime=y" >> .config
                echo "CONFIG_PACKAGE_luci-i18n-base-es=y" >> .config
                echo "CONFIG_PACKAGE_luci-i18n-firewall-es=y" >> .config
                echo "CONFIG_PACKAGE_luci-attendedsysupgrade=y" >> .config
                echo "CONFIG_PACKAGE_luci-i18n-attendedsysupgrade-es=y" >> .config
                echo "CONFIG_PACKAGE_collectd-mod-uptime=y" >> .config
                echo "CONFIG_PACKAGE_htop=y" >> .config
                echo "CONFIG_PACKAGE_diffutils=y" >> .config
                echo "CONFIG_PACKAGE_usteer=y" >> .config
                echo "CONFIG_PACKAGE_jq=y" >> .config
                echo "CONFIG_PACKAGE_fping=y" >> .config
                echo "CONFIG_PACKAGE_arp-scan=y" >> .config

                make defconfig

                cat .config

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: TAR output
              run: tar -cvf ipq807xx-images.tar bin/targets/ipq807x/generic

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: ipq807x-images
                path: ipq807xx-images.tar
